<?php

/* Elementor Check */

function is_elementor($post_id){
	global $post;
	if (is_plugin_active( 'elementor/elementor.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {
		return \Elementor\Plugin::$instance->db->is_built_with_elementor($post_id);
	} else {
		return false;
	}
}

/* Add SEO data to head */

function est_seo_data() {
	global $post;

	// // Get the current post id
	$post_id = $post->ID;


	if ( is_elementor($post_id) ) {
		// Get the page settings manager
		$page_settings_manager = \Elementor\Core\Settings\Manager::get_settings_managers( 'page' );

		// Get the settings model for current post
		$page_settings_model = $page_settings_manager->get_model( $post_id );

		// Retrieve the color we added before
		$focuskw 		= $page_settings_model->get_settings( '_est_seo_focuskw' );
		$seotitle 		= $page_settings_model->get_settings( '_est_seo_title' );
		$seodesc 		= $page_settings_model->get_settings( '_est_seo_metadesc' );

	} else {
		$focuskw 	= get_post_meta( $post_id, '_est_seo_focuskw', true );
		$seotitle 	= get_post_meta( $post_id, '_est_seo_title', true );
		$seodesc 	= get_post_meta( $post_id, '_est_seo_desc', true );
	}
	
	$seofields = '';

	if( !empty( $seotitle ) ) {
		$seofields .= '<!-- Generated by Easy SEO Toolkit - https://easyseotoolkit.com/ -->';
		$seofields .= '<meta name="title" content="'.$seotitle.'">'; 
		$seofields .= '<meta name="twitter:card" content="summary" />';
		$seofields .= '<meta name="twitter:title" content="'.$seotitle.'" />';
	}
	if( !empty( $seodesc ) ) {
		$seofields .= '<meta name="description" content="'.$seodesc.'">';
		$seofields .= '<meta name="twitter:description" content="'.$seodesc.'" />';
	}

	if( has_post_thumbnail( $post->ID ) ) {
		$seofields .= '<meta name="twitter:image" content="'.get_the_post_thumbnail_url($post_id,'full').'" />';		
	}



	$focuskw_html = '';

	if ($focuskw_html === '1') {
		$seofields .= '<meta name="keywords" content="'.$focuskw.'">';
	}
	
	echo $seofields;
	
}
add_action('wp_head', 'est_seo_data');

/* Fix <title></title> tag */

function est_filter_wp_title( $title_parts ) {
	global $post;
	// // Get the current post id
	$post_id = $post->ID;

	if ( is_elementor($post_id) && !is_archive() ) {
		// Get the page settings manager
		$page_settings_manager = \Elementor\Core\Settings\Manager::get_settings_managers( 'page' );

		// Get the settings model for current post
		$page_settings_model = $page_settings_manager->get_model( $post_id );
		
		$seotitle = $page_settings_model->get_settings( '_est_seo_title' );	

	} else {
		$seotitle 	= get_post_meta( $post_id, '_est_seo_title', true );
	}
	
	if( !empty( $seotitle ) ) {
		$title_parts['title'] = $seotitle;
	
		return $title_parts;
	} else {
		if(is_single($post_id) OR is_page($post_id)) {
			$title_parts['title'] = get_the_title();
		}
		else {
			$title_parts['title'] = get_the_archive_title();
		}
	
		return $title_parts;
	}
}
add_filter( 'document_title_parts', 'est_filter_wp_title', 10, 999 );